name: Lint

on:
  push:
    paths:
      - '*.css'

jobs:
  lint:
    name: Check CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Stylelint
        run: npm run stylelint

      - name: Prettier
        run: npm run prettier
